# SPDX-License-Identifier: Apache-2.0
"""RXF v1 (Rhizome Exchange Format).

The Pydantic models are the only source of truth: the validator builds its JSON Schema from them at
runtime, and ``rxf-spec/schema/rxf-v1.schema.json`` is a published copy generated by
``rhz rxf schema`` (a contract test asserts it never drifts).
Field names are fixed English; values may be in any language.

Items may carry a local ``id`` (unique within the file). ``user_insights.links_to`` and
``review_cards.about`` refer to those ids; :func:`reference_problems` checks that every reference
exists. Files without any ids (older exports) keep the old behaviour: references are names.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

RXF_VERSION = 1


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)


class _Item(_Strict):
    id: str | None = Field(None, description="Local id, unique within this file (e.g. c1, m2); "
                                             "user_insights.links_to and review_cards.about refer to it")


PaperType = Literal["research", "tool", "resource", "benchmark", "review", "protocol"]


class Paper(_Strict):
    doi: str | None = Field(None, description="DOI without the https://doi.org/ prefix")
    title: str
    year: int | None = Field(None, ge=1600, le=2100)
    type: list[PaperType] = Field(default_factory=list)
    organisms: list[str] = Field(default_factory=list)
    modalities: list[str] = Field(default_factory=list)
    authors: list[str] = Field(default_factory=list)
    venue: str | None = None
    url: str | None = None

    @field_validator("doi")
    @classmethod
    def _strip_doi(cls, v: str | None) -> str | None:
        if v is None:
            return v
        v = v.strip()
        for prefix in ("https://doi.org/", "http://doi.org/", "doi:", "DOI:"):
            if v.startswith(prefix):
                v = v[len(prefix):]
        return v


class TopicRef(_Item):
    name: str
    relation: Literal["about", "applicable_to"]


class Claim(_Item):
    text: str
    evidence_type: Literal["causal", "correlational", "speculative"]
    evidence: str = Field(description="Location in the paper, e.g. 'Fig. 3B' (required)")
    boundary: str | None = None
    logic_jump: bool = False
    stance: Literal["supports", "contradicts"] = "supports"


class Dataset(_Item):
    accession: str | None = None
    database: Literal["GEO", "SRA", "CNGB", "ArrayExpress", "ENA", "Zenodo", "other"] | None = None
    name: str | None = None
    organism: str | None = None
    tissue: str | None = None
    modality: str | None = None
    scale: str | int | None = None
    public: bool | None = None
    role: Literal["uses", "produces"] = "uses"
    evidence: str | None = None

    @model_validator(mode="after")
    def _needs_identity(self) -> "Dataset":
        if not (self.accession or self.name):
            raise ValueError("dataset needs an accession or a name")
        return self


class Method(_Item):
    name: str
    repo: str | None = None
    biotools: str | None = None
    role: Literal["proposes", "uses", "evaluates"] = "uses"
    io: str | None = None
    maintained: Literal["yes", "no", "unknown"] | bool | None = None
    modality: str | None = None
    extends: list[str] = Field(default_factory=list)
    evidence: str | None = None


class Transfer(_Strict):
    type: Literal["cross-species", "cross-modality", "cross-problem"]
    to: str | None = None
    barrier: str | None = None


class Idea(_Item):
    text: str
    transfer: Transfer | None = None
    origin: Literal["model", "user"] = "model"


class Assets(_Strict):
    datasets: list[Dataset] = Field(default_factory=list)
    methods: list[Method] = Field(default_factory=list)
    ideas: list[Idea] = Field(default_factory=list)


class Issue(_Item):
    severity: Literal["minor", "major", "critical"]
    location: str | None = None
    text: str
    test: str | None = None


class UserInsight(_Item):
    text: str
    links_to: list[str] = Field(default_factory=list, description="ids of items in this file")


class ReviewCard(_Item):
    q: str
    a: str
    about: str | None = Field(None, description="id of the item in this file the card is about")


class RxfDocument(_Strict):
    rxf_version: Literal[1]
    id: str | None = Field(None, description="Id of this export, assigned by the exporting chat")
    exported_at: str | None = Field(None, description="When the export was written (ISO 8601)")
    language: str | None = Field(None, description="Main language of the free-text values, e.g. zh-CN, en")
    prompt_version: str | None = None
    depth: Literal["light", "deep"] = "light"
    paper: Paper
    tldr: list[str] = Field(default_factory=list, max_length=5)
    topics: list[TopicRef] = Field(default_factory=list)
    claims: list[Claim] = Field(default_factory=list)
    assets: Assets = Field(default_factory=Assets)
    issues: list[Issue] = Field(default_factory=list)
    user_insights: list[UserInsight] = Field(default_factory=list)
    review_cards: list[ReviewCard] = Field(default_factory=list)


SCHEMAS: dict[int, type[RxfDocument]] = {1: RxfDocument}

# Kinds an id can point at that become graph nodes; issues and review cards are not nodes.
NODE_KINDS = ("topic", "claim", "dataset", "method", "idea", "user_insight")


_ID_LISTS = (("topic", ("topics",)), ("claim", ("claims",)), ("dataset", ("assets", "datasets")),
             ("method", ("assets", "methods")), ("idea", ("assets", "ideas")), ("issue", ("issues",)),
             ("user_insight", ("user_insights",)), ("review_card", ("review_cards",)))


def _items(data: dict):
    """(kind, path, index, item) for every mapping item of the id-carrying lists. Works on the raw
    parsed document, so reference problems are reported together with schema problems."""
    for kind, keys in _ID_LISTS:
        cur = data
        for k in keys:
            cur = cur.get(k) if isinstance(cur, dict) else None
        for i, it in enumerate(cur if isinstance(cur, list) else []):
            if isinstance(it, dict):
                yield kind, ".".join(keys), i, it


def _id(it: dict) -> str | None:
    v = it.get("id")
    return str(v).strip() or None if v is not None else None


def declared_ids(data: dict) -> dict[str, str]:
    """id -> kind for every item that declares one (first declaration wins)."""
    out: dict[str, str] = {}
    for kind, _path, _i, it in _items(data):
        if (k := _id(it)) and k not in out:
            out[k] = kind
    return out


def uses_ids(doc: RxfDocument) -> bool:
    return bool(declared_ids(doc.model_dump()))


def reference_problems(data: dict) -> list[tuple[str, str, str]]:
    """Cross-reference checks the JSON Schema cannot express: (path, kind, value) triples with
    kind ``duplicate_id``, ``bad_reference`` (no such id) or ``not_a_node`` (id of an issue/card)."""
    problems: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for _kind, path, i, it in _items(data):
        if k := _id(it):
            if k in seen:
                problems.append((f"{path}.{i}.id", "duplicate_id", k))
            seen.add(k)
    if not seen:
        return problems  # older export without ids: references are names, resolved against the library
    ids = declared_ids(data)

    def check(path: str, ref) -> None:
        ref = str(ref).strip()
        if ref not in ids:
            problems.append((path, "bad_reference", ref))
        elif ids[ref] not in NODE_KINDS:
            problems.append((path, "not_a_node", ref))

    for _kind, path, i, it in _items(data):
        if _kind == "user_insight" and isinstance(it.get("links_to"), list):
            for j, ref in enumerate(it["links_to"]):
                if isinstance(ref, (str, int)):
                    check(f"{path}.{i}.links_to.{j}", ref)
        if _kind == "review_card" and isinstance(it.get("about"), (str, int)):
            check(f"{path}.{i}.about", it["about"])
    return problems


def json_schema(version: int = RXF_VERSION) -> dict:
    schema = SCHEMAS[version].model_json_schema()
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["$id"] = f"https://rhizome.local/rxf/v{version}.schema.json"
    schema["title"] = f"RXF v{version}"
    return schema
