# SPDX-License-Identifier: Apache-2.0
"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 05:31:20.739569
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('entity_key', sa.String(length=255), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity_key')
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('type', 'external_id')
    )
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_type'), ['type'], unique=False)

    op.create_table('extraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('work_key', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('input_hashes', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_work_key'), ['work_key'], unique=False)

    op.create_table('human_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('op', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_status'), ['status'], unique=False)

    op.create_table('kv',
    sa.Column('k', sa.String(length=128), nullable=False),
    sa.Column('v', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('raw_object',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('work_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    with op.batch_alter_table('raw_object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_object_work_key'), ['work_key'], unique=False)

    op.create_table('review_card',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_key', sa.String(length=255), nullable=False),
    sa.Column('q', sa.Text(), nullable=False),
    sa.Column('a', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('due', sa.DateTime(), nullable=True),
    sa.Column('introduced_at', sa.DateTime(), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_card_due'), ['due'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_card_entity_key'), ['entity_key'], unique=False)

    op.create_table('review_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('review_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_item_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_item_status'), ['status'], unique=False)

    op.create_table('review_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_log_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_log_reviewed_at'), ['reviewed_at'], unique=False)

    op.create_table('vector_cache',
    sa.Column('text_sha', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('vec', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('text_sha', 'model')
    )
    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.Integer(), nullable=False),
    sa.Column('dst', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dst'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src', 'dst', 'type')
    )
    with op.batch_alter_table('edge', schema=None) as batch_op:
        batch_op.create_index('ix_edge_dst_type', ['dst', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_edge_src'), ['src'], unique=False)

    op.create_table('embedding',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vec', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', 'model')
    )
    op.create_table('entity_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('norm', sa.String(length=512), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'norm')
    )
    with op.batch_alter_table('entity_alias', schema=None) as batch_op:
        batch_op.create_index('ix_alias_norm', ['norm'], unique=False)

    op.create_table('work',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('openalex_id', sa.String(length=32), nullable=True),
    sa.Column('dois', sa.JSON(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('openalex_id')
    )
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "sqlite":
        # trigram tokenizer: substring matching for CJK and Latin text without a segmenter
        op.execute("create virtual table entity_fts using fts5(text, entity_id unindexed, tokenize='trigram')")


def downgrade() -> None:
    if op.get_bind().dialect.name == "sqlite":
        op.execute("drop table if exists entity_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    with op.batch_alter_table('entity_alias', schema=None) as batch_op:
        batch_op.drop_index('ix_alias_norm')

    op.drop_table('entity_alias')
    op.drop_table('embedding')
    with op.batch_alter_table('edge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edge_src'))
        batch_op.drop_index('ix_edge_dst_type')

    op.drop_table('edge')
    op.drop_table('vector_cache')
    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_log_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_review_log_card_id'))

    op.drop_table('review_log')
    with op.batch_alter_table('review_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_item_status'))
        batch_op.drop_index(batch_op.f('ix_review_item_kind'))

    op.drop_table('review_item')
    with op.batch_alter_table('review_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_card_entity_key'))
        batch_op.drop_index(batch_op.f('ix_review_card_due'))

    op.drop_table('review_card')
    with op.batch_alter_table('raw_object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_object_work_key'))

    op.drop_table('raw_object')
    op.drop_table('kv')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_status'))

    op.drop_table('job')
    op.drop_table('human_decision')
    with op.batch_alter_table('extraction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_work_key'))
        batch_op.drop_index(batch_op.f('ix_extraction_is_current'))

    op.drop_table('extraction')
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_type'))

    op.drop_table('entity')
    op.drop_table('access_log')
    # ### end Alembic commands ###
